name: Deploy Docker CI
on:
    workflow_dispatch:
    push:
        branches:
            - main
jobs:
    publish_to_docker:
        runs-on: ubuntu-latest
        steps:
            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push
              id: docker_build
              uses: docker/build-push-action@v2
              with:
                  push: true
                  tags: panda01dev/hana:latest

    run_on_server:
        needs: publish_to_docker
        runs-on: ubuntu-latest
        steps:
            - name: executing remote ssh commands using password
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  password: ${{ secrets.SSH_PASSWORD }}
                  port: ${{ secrets.SSH_PORT }}
                  script: |
                      echo "${{ secrets.DOCKER_PASSWORD }}" | sudo docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
                      sudo docker rm -f $(docker ps -aq -f name=hana)
                      sudo docker rmi $(docker images | grep 'panda01dev/hana' | awk '{print $3}')
                      sudo docker pull panda01dev/hana
                      sudo docker run -e DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} -e DISCORD_GENERAL_CHANNEL_ID=${{ secrets.DISCORD_GENERAL_CHANNEL_ID}} -d --restart always --name hana-instance panda01dev/hana
